# .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends make

      - name: Install Python dependencies
        run: make setup

      - name: Run all PoC attacks
        run: make all

      - name: Validate PoC results
        run: |
          test -f results/extraction_plot.png
          test -f results/membership_roc.png
          test -f results/tabular_adv_plot.png